# Run parallel jobs to sum each of the several plays.* partial files.
log    =    log/words-chtc_$(Cluster)_$(proc).log
error  =  error/words-chtc_$(Cluster)_$(proc).err
output = output/words-chtc_$(Cluster)_$(proc).out

universe = vanilla
proc=$INT(Process,%02d)

executable = ./job.sh
arguments = $(proc)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = plays.$(proc)

request_cpus = 1
request_memory = 1GB
request_disk = 6MB

queue 5

